[package]
name = "rnostr"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "1.6.0", features = ["full"] }
hyper-tungstenite = "0.18.0"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
secp256k1 = { version = "0.31.0", features = ["rand", "global-context"] }
sha2 = "0.10"
url = "2.4"
thiserror = "1.0"
unicode-normalization = "0.1"
heed = "0.20"
dashmap = "6.1"
fasthash = "0.4"
lazy_static = "1.4"
tracing = "0.1"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
bech32 = "0.11.0"
regex = "1.11.1"
tokio-tungstenite = { version = "0.27.0", features = ["rustls-tls-native-roots"] }
bytes = "1.10.1"
http-body-util = "0.1.3"
hyper-util = { version = "0.1.14", features = ["tokio"] }
reqwest = { version = "0.12.20", default-features = false, features = ["json", "rustls-tls"] }
lowercase-hex = "0.1.0"
ahash = "0.8.12"
slotmap = "1.0.7"
glidesort = "0.1.2"

[dev-dependencies]
tempfile = "3.0"
