[package]
name = "rnostr"
version = "0.1.0"
edition = "2021"
description = "Core Nostr protocol types and utilities"
license = "MIT"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = { version = "0.20", features = ["native-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
secp256k1 = { version = "0.28", features = ["rand", "recovery", "global-context"] }
sha2 = "0.10"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
url = "2.4"
futures = "0.3"
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
rand = "0.8"
bytes = "1.0"
dashmap = "5.5"
nonempty = { version = "0.11.0", features = ["serialize"] }
bech32 = "0.9"
chacha20poly1305 = "0.10"
scrypt = "0.11"
unicode-normalization = "0.1"
reqwest = { version = "0.11", features = ["json"] }
regex = "1.0"
lazy_static = "1.4"
heed = "0.20"
fasthash = "0.4.0"
